try multiple approaches at once for unit test workflow

diff --git a/.github/workflows/phpunit.yml b/.github/workflows/phpunit.yml
--- a/.github/workflows/phpunit.yml
+++ b/.github/workflows/phpunit.yml
@@ -27,11 +27,25 @@ jobs:
 
     name: OpenConnector (PHP 8.3)
 
+    services:
+      cache:
+        image: ghcr.io/nextcloud/continuous-integration-redis:latest
+        ports:
+          - 6379:6379/tcp
+        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
+
     steps:
       - name: Checkout openconnector
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
         with:
           submodules: true
+
+      - name: Checkout Nextcloud server
+        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
+        with:
+          repository: nextcloud/server
+          path: server
+          token: ${{ secrets.GITHUB_TOKEN }}
 
       - name: Set up php 8.3
         uses: shivammathur/setup-php@2e947f1f6932d141d076ca441d0e1e881775e95b #v2.31.0
@@ -41,8 +55,24 @@ jobs:
           coverage: none
           ini-file: development
 
-      - name: Install dependencies
-        run: composer install
+      - name: Set up dependencies
+        run: cd server && composer i
+
+      - name: Copy openconnector app to server
+        run: |
+          cp -r . server/apps-extra/openconnector
+
+      - name: Set up Nextcloud
+        run: |
+          cd server
+          mkdir data
+          cp tests/redis.config.php config/
+          cp tests/preseed-config.php config/config.php
+          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
+          php -f tests/enable_all.php | grep -i -C9999 error && echo "Error during app setup" && exit 1 || exit 0
+
+      - name: Enable OpenConnector app
+        run: cd server && ./occ app:enable openconnector
 
       - name: Run PHPUnit tests
-        run: composer test:unit
+        run: cd server && phpunit --bootstrap tests/bootstrap.php apps-extra/openconnector/tests
